---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: patch-machinepool
spec:
  workspaces:
  - name: source
  params:
    - name: machinepool_name
      description: The machinepool name
      type: string
      default: "k8s"
    - name: cluster_namespace
      description: The namespace of the managed cluster definition
      type: string
      default: "k8s"
    - name: node_count
      description: The node count for this machineset
      type: string
      default: "3"
  steps:
    - name: apply
      image: quay.io/openshift/origin-cli:latest
      workingDir: /workspace/source
      command: ["/bin/bash", "-c"]
      args:
        - |-
          echo Patching machinepool $(inputs.params.machinepool_name) to $(inputs.params.node_count) replicas
          oc -n $(inputs.params.cluster_namespace) patch machinepool ${inputs.params.machinepool_name} --type merge -p '{ "spec": { "replicas": $(inputs.params.node_count) } }'
          echo -----------------------------------
