---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubeconfig-pvc
  namespace: pipelines-demo
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
